### ISSUE TITLE
OperationalError: "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE)..."

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#119]
Message type:       ERROR
Time:               2015-03-20 00:03:00,990

Exception on /trackman/api/search [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./wuvt/trackman/view_utils.py", line 14, in local_wrapper
    return f(*args, **kwargs)
  File "./wuvt/trackman/view_utils.py", line 21, in dj_wrapper
    ret = f(*args, **kwargs)
  File "./wuvt/trackman/admin_views.py", line 528, in search_tracks
    tracks = tracks.limit(8).all()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2286, in all
    return list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2398, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2413, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 717, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 814, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 927, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1076, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 185, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 920, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 425, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (OperationalError) (1267, "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='") 'SELECT track.id AS track_id, track.title AS track_title, track.artist AS track_artist, track.album AS track_album, track.label AS track_label, track.added AS track_added, count(track.id = tracklog.track_id) AS count_1 \nFROM track LEFT OUTER JOIN tracklog ON track.id = tracklog.track_id \nWHERE lower(track.artist) = lower(%s) AND lower(track.title) = lower(%s) AND lower(track.album) = lower(%s) AND lower(track.label) = lower(%s) GROUP BY track.id, track.title, track.artist, track.album, track.label, track.added ORDER BY count(track.id = tracklog.track_id) DESC \n LIMIT %s' ('Beastie Boys', 'Girls', 'Licensed to Ill', '\xe2\x88\x82', 8)

**Comment by telnoratti** [comment]
| character_set_database                            | latin1. Our database does not appear to be utf8.

ALTER DATABASE databasename CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE tablename CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
From http://stackoverflow.com/questions/6115612/how-to-convert-an-entire-mysql-database-characterset-and-collation-to-utf-8

I would like a second opinion before I do an alter table or alter database.

**Comment by matthazinski** [comment]
I don't know SQL very well; I'd just make a backup and do it in a transaction so it's easy to roll back if something breaks.

**Comment by telnoratti** [comment]
I don't think SQL alchemy can fix this, it would have had to be done at table creation time.

**Comment by mutantmonkey** [comment]
All the columns are already set to be Unicode. The collation needs to be fixed in the database, and someone should figure out why MariaDB didn't do this by default when it's 2015 and we use Unicode now.

**Comment by mutantmonkey** [comment]
I added `?charset=utf8&use_unicode=0` to the SQLALCHEMY_DATABASE_URI and ran the following:
```
use wuvtsite;
select @@character_set_database, @@colation_database;
select @@character_set_database, @@collation_database;
alter database wuvtsite character set utf8 collate utf8_unicode_ci;
show table status;
alter table air_log convert to character set utf8;
alter table article convert to character set utf8;
alter table category convert to character set utf8;
alter table dj convert to character set utf8;
alter table page convert to character set utf8;
alter table rotation convert to character set utf8;
alter table set convert to character set utf8;
alter table `set` convert to character set utf8;
alter table track conver to character set utf8;
alter table track convert to character set utf8;
alter table tracklog convert to character set utf8;
alter table trackreport convert to character set utf8;
alter table user convert to character set utf8;
```

That seems to have fixed this issue; columns seem to be able to store Unicode things now: https://www.wuvt.vt.edu/playlists/set/222
