### ISSUE TITLE
Still broken when OIDC is enabled

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#451]
```
Traceback (most recent call last):
  File "/usr/src/app/./wuvt/__init__.py", line 122, in <module>
    auth_manager.init_app(app)
  File "/usr/src/app/./wuvt/auth/auth_manager.py", line 42, in init_app
    google_bp = create_flask_blueprint([Google], self.oauth,
  File "/usr/local/lib/python3.9/site-packages/loginpass/_flask.py", line 38, in create_flask_blueprint
    register_to(oauth, b)
  File "/usr/local/lib/python3.9/site-packages/loginpass/_flask.py", line 83, in register_to
    from authlib.integrations.flask_client import FlaskRemoteApp
ImportError: cannot import name 'FlaskRemoteApp' from 'authlib.integrations.flask_client' (/usr/local/lib/python3.9/site-packages/authlib/integrations/flask_client/__init__.py)
```

**Comment by mutantmonkey** [comment]
It looks like this is an incompatibility between loginpass 0.5 and authlib>=1.0.0. We can pin an older version of authlib for the time being until the issue is resolved.
