### ISSUE TITLE
Track logging ascii codec error

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#79]
payload: {'album': 'The ArchAndroid (Suites II and III)', 'password': '<redacted>', 'artist': 'Janelle Mon\xc3\xa1e', 'title': 'Wondaland'}

Exception on /trackman/api/automation/log [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./wuvt/trackman/view_utils.py", line 13, in _wrapper
    return f(*args, **kwargs)
  File "./wuvt/trackman/admin_views.py", line 137, in automation_log
    log_track(track.id, djset_id)
  File "./wuvt/trackman/lib.py", line 85, in log_track
    song = '{artist} - {title}'.format(artist=artist, title=title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 11: ordinal not in range(128)

**Comment by telnoratti** [comment]
I'm not sure the best way to handle this, can Icecast accept unicode? If so this might be as simple as making these unicode strings. On that note can TuneIn and LastFM?

**Comment by matthazinski** [comment]
IIRC TuneIn and Icecast both use url-encoded parameters so they should support UTF-8 but not Unicode.
